spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  mongodb:
    embedded:
      version: 5.0.5
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: banana
#      password: banana
#      database: banana

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env", "httptrace"]
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  project:
    version: @project.version@
  java:
    version: @java.version@
  spring:
    framework:
      version: @spring-framework.version@
    data:
      version: @spring-data-bom.version@

logging:
  level:
    org.springframework.amqp: debug
    org.springframework.messaing: debug
    reactor: debug